### ISSUE TITLE
Extract course title from Class Schedule Listings page and Details Course Info page

### ISSUE THREAD

**Issue by aomi** [VikeLabs/scheduler-scraper#131]
As mentioned https://github.com/VikeLabs/courseup/discussions/220, topic courses have their titles not in the calendar. We didn't initially scrape this as we assumed the title would be the same. Clearly this assumption was wrong.

Add a `title` attribute to the respective types/interfaces. and add the parser code in the appropriate files (likely under the `src/pages/courseListingEntries` and `src/pages/detailedClassInformation` within the extractor function already there.

Parsing the title should not contain extra info like the CRN etc. The example of this in action would be:
Before Parsing:
> TOPICS:SOFTWARE ENGINEER: Quantum Algorithms and Software Engineering - 32729 - SENG 480C - A01

Parsed:
> TOPICS:SOFTWARE ENGINEER: Quantum Algorithms and Software Engineering

**Comment by NishchintDhawan** [comment]
Sounds good.
