### ISSUE TITLE
Gather additional Course Data

### ISSUE THREAD

**Issue by kerfootj** [VikeLabs/scheduler-scraper#15]
# User Story
As a student, I want information about the courses available to me.

# Description
Currently we are only scraping course codes, subjects, titles, terms, and crns. At a minimum we need to get the following addition information:
* meeting times: day of week, time, location, start date, and end date
* section information: type and number, eg A01
* course description
* instructor(s) information

# Additional Details 
See [example.json](https://github.com/VikeLabs/scheduler-scraper/blob/master/example.json) for more details on how the information can be formatted

# Acceptance Criteria
- [ ] The data mentioned above is acquired for each course

**Comment by rmcilwain6** [comment]
Pushed a commit for this, just changed the crn field into a Section object with crn, section type and section number
