### ISSUE TITLE
Download HTML files of detailed class information to the repository

### ISSUE THREAD

**Issue by keithradford** [VikeLabs/scheduler-scraper#31]
We want to have local copies of the HTML for the detailed class information for every section of every class in our repository so we can avoid continuously sending requests to UVIC's website. It'll also let us have easy access to files for development and testing our code.
Here's an example of a detailed class information page: https://www.uvic.ca/BAN1P/bwckschd.p_disp_detail_sched?term_in=202005&crn_in=30184
You'd be directly ripping the HTML of this page into a local file.

Things to consider for this task:
- Naming convention for HTML files (Keep it consistent and possible to tell what section it is i.e. ECE360_<CRN>.html)

- How will we know the files are up to date? (JSON file that has the date the HTML file was uploaded to the repo 
i.e. {
         'ECE360_1234.html': '2020/10/26',
...
}

- If an HTML file exists already for a section, replace that code with updated code

- Should remove classes no longer active (i.e. if a new semester starts)

**Comment by isaaccormack** [comment]
likely closed by #51
