### ISSUE TITLE
Scrape data off the UVic Class Schedule Listing pages

### ISSUE THREAD

**Issue by kerfootj** [VikeLabs/scheduler-scraper#9]
# User Story
As a developer, I want to be able to scrape information off of the Class Schedule Listing

# Description
Assuming the web scraper/crawler is capable of reaching each Class Schedule Listing ([example](https://www.uvic.ca/BAN1P/bwckctlg.p_disp_listcrse?term_in=201905&subj_in=SENG&crse_in=265&schd_in=)) gather as much useful class information as possible.

# Additional Details 
An example of all the information that can be gathered for one class:
```json
{ 
   "crn":"20187",
   "description":"Please register in the lab dedicated to this lecture (B01).",
   "section_type":"A",
   "section_number":"01",
   "reg_start":"2018-06-18T00:00:00",
   "reg_end":"2019-01-23T00:00:00",
   "attributes":"Undergrad Course - 1.5 units",
   "campus":"Main Campus",
   "schedule_type_alt":"Lecture Schedule Type",
   "method":"Face to Face Instructional Method",
   "credits":"1.500 Credits",
   "meeting_times":[ 
      { 
         "type":"Every Week",
         "time":"11:30 am - 1:20 pm",
         "days":"M",
         "location":"Clearihue Building A303",
         "start_date":"2019-01-07T00:00:00",
         "end_date":"2019-04-05T00:00:00",
         "schedule_type":"Lecture",
         "instructors":[ 
            { 
               "name":"Tim J. Lane",
               "email":"lanetj@uvic.ca"
            }
         ]
      }
   ]
},
```

# Acceptance Criteria
- [ ] Create a scraper that works on any Class Schedule Listing page
- [ ] It should return an array of all classes available on the page

**Comment by kerfootj** [comment]
@RyanBarclay I think this is something that you can work on. Assign it to yourself if it's something you want to work on.

**Comment by kerfootj** [comment]
Outdated

**Comment by ColinGJohnson** [comment]
Nice example 🥇
